const exhb=require('express-handlebars');
const express=require('express');
const methodoverride=require('method-override');
const bodyparser=require('body-parser');
const app=express();
app.use(bodyparser.urlencoded({extended:false}));
app.use(bodyparser.json());
app.use(methodoverride("_method"));
app.engine("hbs",exhb());
app.set("view engine","hbs");